"App: Data Importer": "apps/data-importer/**/*"
"App: Klaviyo": "apps/klaviyo/**/*"
"App: Product Feed": "apps/products-feed/**/*"
"App: Search": "apps/search/**/*"
"App: Avatax": "apps/avatax/**/*"
"App: Emails & Messages": "apps/emails-and-messages/**/*"
"App: CMS": "apps/cms-v2/**/*"
"App: SMTP": "apps/smtp/**/*"
