repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      -   id: check-toml
      -   id: check-yaml
      -   id: end-of-file-fixer
          exclude_types: [svg]
          exclude: ^generated
      -   id: trailing-whitespace
          exclude_types: [svg]
          exclude: ^generated
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        files: ^backend/
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.215
    hooks:
      - id: ruff
        args: ["--config", "backend/pyproject.toml"]
        files: ^backend/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: ["--config-file=backend/pyproject.toml"]
        language: system
        files: ^backend/
