name: Changesets

on:
  pull_request:
    types:
      - opened
      - labeled
      - edited
      - synchronize
jobs:
  changeset_check:
    name: Changeset added to the PR
    # Adding 'skip changesets' label to the PR will skip this job
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip changeset') && !startsWith(github.head_ref, 'changeset-release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # check out full history
          fetch-depth: 0
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          run_install: |
            - args: [--frozen-lockfile]
      - name: Changeset added
        run: pnpm changeset status --since origin/main
