name: E2E staging (label)
on:
  pull_request:
    types: [labeled]

jobs:
  run:
    if: ${{ github.event.label.name == 'run e2e' }}
    uses: saleor/apps/.github/workflows/e2e.yml@update-e2e-workflow-dispatch
    secrets:
      saleor_token: ${{ secrets.SALEOR_TOKEN }}
      op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
