name: E2E staging (label)
on:
  pull_request:
    types: [labeled]

jobs:
  e2e-label:
    if: ${{ github.event.label.name == 'run e2e' }}
    uses: saleor/apps/.github/workflows/e2e.yml@update-e2e-workflow-dispatch
